import React,{useState} from 'react';
import {Range,Select,Note,Submit,Result,Sparkline} from './Primitives.jsx';
import {GRID,WALLS,START,GOAL,transition,trainQ,rollout,documents,retrieve,validateTicket} from '../../journeys/models.js';

export function RLLab({stage,data,setData,commit}){
 const [cell,setCell]=useState(START);const path=data.path??[START],position=path.at(-1),reward=data.shortcut??-3,epsilon=data.epsilon??.25,run=data.qRun,changed=data.changed??false;
 const evaluation=run?rollout(run.q,{shortcut:run.shortcut,changed}):null,shown=stage>=2&&evaluation?evaluation.path:path;
 function move(action){const t=transition(position,action,{shortcut:reward});setData({path:[...path.slice(-40),t.next],return:(data.return??0)+t.reward});}
 return <><h2>{['先用自己的动作理解环境','奖励怎么设，策略就怎么学','用经验更新 Q(s, a)','环境变了，旧策略还可靠吗？'][stage]}</h2><div className="rl-arena"><section><div className="grid-world" role="group" aria-label="五乘五环境，点格子查看动作价值">{Array.from({length:25},(_,i)=><button key={i} onClick={()=>setCell(i)} className={[WALLS.includes(i)||(changed&&stage===3&&i===3)?'wall':'',i===cell?'selected':'',shown.includes(i)?'visited':''].join(' ')} aria-label={`状态 ${i}${i===GOAL?' 出口':''}${WALLS.includes(i)?' 障碍':''}`}><span>{i===GOAL?'出口':i===START?'起点':i===13?'捷径':WALLS.includes(i)?'':i}</span>{i===position&&stage<2&&<b>N</b>}{stage>=2&&shown.includes(i)&&!WALLS.includes(i)&&i!==GOAL&&<small>{['↑','→','↓','←'][run?.q[i].indexOf(Math.max(...run.q[i]))]}</small>}</button>)}</div><div className="work-actions">{['上','右','下','左'].map((label,a)=><button className="secondary" key={label} disabled={position===GOAL} onClick={()=>move(a)}>{label}</button>)}<button className="text-button" onClick={()=>setData({path:[START],return:0})}>重新出发</button></div><p>手动轨迹：{path.join(' → ')} · 回报 {data.return??0}</p></section><section className="q-inspector"><h3>环境规则</h3><p>到达出口 +10；普通移动 −1；撞墙仍计一步。到出口终止，最多 80 步截断一轮。</p><Range label="经过捷径的奖励" value={reward} onChange={shortcut=>setData({shortcut})} min={-8} max={5} step={1}/><Range label="探索率 ε" value={epsilon} onChange={epsilon=>setData({epsilon})} min={0} max={1} step={.05}/><button className="primary" onClick={()=>setData({qRun:trainQ(180,epsilon,reward),changed:false})}>训练 180 个回合</button>{run&&<><h3>状态 {cell} 的 Q 值</h3><div className="q-values">{['上','右','下','左'].map((l,a)=><span key={l}>{l}<b>{run.q[cell][a].toFixed(2)}</b></span>)}</div><p>本次种子 {run.seed} · α=0.3 · γ=0.9 · ε={run.epsilon}</p></>}{stage===3&&<label className="work-check"><input type="checkbox" checked={changed} onChange={e=>setData({changed:e.target.checked})}/>在状态 3 增加一个障碍，用旧 Q 表复测</label>}</section></div>{run&&<><Sparkline series={[run.returns]} labels={['每回合回报']}/><Result ok={evaluation.success}>{evaluation.success?`当前贪心策略到达出口，${evaluation.path.length-1} 步，回报 ${evaluation.total}。`:`旧策略在 35 步内未到达出口，回报 ${evaluation.total}。它需要新的经验，不能自动适应环境变化。`}</Result></>}<pre>Q(s,a) ← Q(s,a) + 0.3 × [r + 0.9 × max Q(s′,·) − Q(s,a)]</pre><Note>终止状态的后续价值取 0。这里实现表格 Q-learning；DQN、PPO 等另见知识页，不能把这份 Q 表称为神经网络策略。正捷径奖励可能诱导绕圈，这是需要观察的失败结果。</Note><Submit disabled={stage<2?path.length<2:!run} onClick={()=>commit(stage<2?`手动回报 ${data.return??0}；奖励方案：捷径 ${reward}。`:`Q-learning 180 回合；探索率 ${run.epsilon}；复测 ${evaluation.success?'到达出口':'失败'}，回报 ${evaluation.total}。`)}>保存轨迹与策略证据</Submit></>;
}

export function LLMLab({stage,data,setData,commit}){
 const query=data.query??'定制商品能七天无理由退货吗？',current=data.current??false,found=retrieve(query,current),tool=data.tool??'{"order_id":104,"reason":"refund","auto_refund":true}',errors=validateTicket(tool),[checked,setChecked]=useState(false);
 const selected=documents.find(d=>d.id===data.source),supported=selected?.id==='P-2026'&&found.some(d=>d.id===selected.id)&&query.includes('定制')&&['退货','无理由'].some(w=>query.includes(w)),answer=supported?'根据现行规则，定制商品不适用七天无理由退货；如果有质量问题，需要人工审核。[P-2026]':'现有选择不足以支持准确答复，应先补齐现行政策。';
 return <><h2>{['先审资料，再谈回答质量','把检索结果与版本放在一起看','模型输出还要过程序校验','只交付证据能支持的部分'][stage]}</h2><div className="evidence-workbench"><section><label className="work-field">用户的问题<input value={query} maxLength={200} onChange={e=>setData({query:e.target.value})}/></label><label className="work-check"><input type="checkbox" checked={current} onChange={e=>setData({current:e.target.checked})}/>检索前过滤掉过期资料</label><h3>虚构客服政策 · 教学证据库</h3><Note>下面是本练习编写的规则，不能当作实际平台政策。</Note>{documents.map(d=><button key={d.id} className={'evidence-doc '+(data.source===d.id?'selected':'')} onClick={()=>setData({source:d.id})}><span>{d.id} · {d.title}</span><p>{d.text}</p><small>{d.current?'现行':'已过期'} · 点击作为答复依据</small></button>)}</section><section><h3>检索轨迹</h3><ol className="retrieval-trace">{found.length?found.map(d=><li key={d.id}><code>{d.id}</code><span>命中 {d.score} 个查询词</span><small>{d.current?'版本有效':'版本过期'}</small></li>):<li>没有匹配证据；应停止回答并请求更多资料。</li>}</ol><Note>为便于检查，这里用关键词匹配排序，没有调用向量模型或在线大模型。检索分数只代表命中，不代表政策权威性。</Note>{stage>=2&&<><label className="work-field">create_support_ticket 参数<textarea className="json-input" value={tool} maxLength={2000} onChange={e=>{setData({tool:e.target.value});setChecked(false);}}/></label><p>order_id: N 加四位数字；reason: quality 或 delivery；不接受额外字段。</p><button className="secondary" onClick={()=>setChecked(true)}>运行参数校验</button>{checked&&<Result ok={!errors.length}>{errors.length?errors.join('；'):'参数符合约定，可以进入人工工单队列。此实验不创建真实工单。'}</Result>}</>}{stage===3&&<section className="answer-proof"><h3>可支持的答复</h3><p>{answer}</p><span>引用：{selected?.id??'未选择'}</span><Note>这是依据选择拼装的示范答复，不是在线模型生成。微调不能替代资料更新、证据核验与工具权限约束。</Note></section>}</section></div><Submit disabled={!supported||(stage>=2&&(errors.length>0||!checked))} onClick={()=>commit(stage<2?'用现行 P-2026 支持定制退货例外；旧政策不能作为当前依据。':'已核验 P-2026 引用与工单 JSON；未执行退款或真实工单。')}>保存审计证据</Submit></>;
}
