import React,{useState} from 'react';
import {Range,Select,Note,Submit,Result,Sparkline} from './Primitives.jsx';
import {marketingData,heldoutData,classification} from '../../journeys/models.js';

export {default as MathLab} from './MathLab.jsx';

export function MLLab({stage,data,setData,commit}){
 const t=data.threshold??.5,fp=data.fp??2,fn=data.fn??5,budget=data.budget??8,filter=data.filter??'all';
 const frozen=data.frozen,opened=stage===3&&!!frozen;
 const rows=opened?heldoutData:marketingData,threshold=opened?frozen.threshold:t,c=classification(rows,threshold,opened?frozen.fp:fp,opened?frozen.fn:fn);
 const filtered=rows.filter(r=>filter==='all'||(filter==='fp'?r.score>=threshold&&!r.label:r.score<threshold&&r.label));
 const candidates=[...new Set([0,1,...marketingData.map(r=>r.score)])].map(threshold=>({threshold,...classification(marketingData,threshold,fp,fn)})).filter(r=>r.count<=budget).sort((a,b)=>a.cost-b.cost);
 const best=candidates[0];
 return <><h2>{['先明确这是一项预测决策','拖动阈值，代价也会跟着变化','从一个错误格子回到具体样本','方案冻结以后，再看保留数据'][stage]}</h2><p>20 条验证样本来自教学合成数据。正类表示后续购买，分数不是因果效果；下方成本是假设损失，不能当作营销增量收益。</p><div className="decision-layout"><section className="decision-controls"><h3>{opened?'已冻结的方案':'决策条件'}</h3><Range label="分类阈值" disabled={opened} value={threshold} onChange={threshold=>{if(!opened)setData({threshold});}} min={0} max={1} step={.01}/>{!opened&&<><Range label="误报成本" value={fp} onChange={fp=>setData({fp})} min={1} max={10} step={1}/><Range label="漏报成本" value={fn} onChange={fn=>setData({fn})} min={1} max={15} step={1}/><Range label="最多触达人数" value={budget} onChange={budget=>setData({budget})} min={1} max={20} step={1}/></>}<pre>{`损失 = FP × ${opened?frozen.fp:fp} + FN × ${opened?frozen.fn:fn}\n     = ${c.fp} × ${opened?frozen.fp:fp} + ${c.fn} × ${opened?frozen.fn:fn}\n     = ${c.cost}`}</pre><p>触达 {c.count} / {opened?frozen.budget:budget} 人 · 精确率 {c.precision===null?'未定义':(c.precision*100).toFixed(1)+'%'} · 召回率 {(c.recall*100).toFixed(1)}%</p>{!opened&&best&&<button className="text-button" onClick={()=>setData({threshold:best.threshold})}>查看此预算下最低验证损失的阈值 {best.threshold.toFixed(2)}</button>}</section><section><h3>{opened?'保留集结果':'验证集结果'}</h3><div className="confusion-grid">{[['tp','预测购买 / 实际购买'],['fp','预测购买 / 实际未购'],['fn','预测未购 / 实际购买'],['tn','预测未购 / 实际未购']].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setData({filter:['fp','fn'].includes(key)?key:'all'})}><span>{label}</span><b>{c[key]}</b><small>{key.toUpperCase()}</small></button>)}</div><Select label="样本视图" value={filter} onChange={filter=>setData({filter})} options={[["all",'全部样本'],['fp','只看误报 FP'],['fn','只看漏报 FN']]}/><div className="sample-table"><table><thead><tr><th>样本</th><th>分数</th><th>实际购买</th><th>触达</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.score.toFixed(2)}</td><td>{r.label?'是':'否'}</td><td>{r.score>=threshold?'是':'否'}</td></tr>)}</tbody></table></div></section></div>{stage===3&&!opened?<><Result ok={c.count<=budget}>{c.count<=budget?'当前方案符合预算。打开保留集后，这次报告的阈值和成本不再变化。':'当前方案超出触达预算，请回到验证集调整。'}</Result><Submit disabled={c.count>budget} onClick={()=>{setData({frozen:{threshold:t,fp,fn,budget},filter:'all'});commit(`冻结阈值 ${t}，预算 ${budget}，误报/漏报成本 ${fp}/${fn}。`);}}>冻结方案，打开保留集</Submit></>:<Submit disabled={!opened&&c.count>budget} onClick={()=>commit(`${opened?'保留集':'验证集'}：阈值 ${threshold}，FP=${c.fp}，FN=${c.fn}，假设损失=${c.cost}。`)}>保存决策记录</Submit>}{opened&&<Note>保留集只用于这份冻结方案的报告。若看完测试结果再调参，这个集合就不再是独立验收集，需要另取新数据。</Note>}</>;
}
