import React,{useEffect,useRef,useState} from 'react';
import {Range,Select,Note,Submit,Result,Sparkline} from './Primitives.jsx';
import {reviews,vocabulary,encode,evaluate,forward,attention,validModel} from '../../journeys/dl-model.js';
import {saveFile} from '../../journeys/records.js';

function FeatureVector({text}){return <div className="feature-vector">{encode(text).map((n,i)=><span key={i} className={n?'on':''}><small>{vocabulary[i]}</small><b>{n}</b></span>)}</div>;}
function Brief({data,setData,commit}){
 const [error,setError]=useState(''),example=data.example??'包装完整，质量不错';
 return <><div className="project-brief-grid"><section><h2>你收到了一项新任务。</h2><div className="project-letter"><dl><dt>发件人</dt><dd>内容运营组</dd><dt>主题</dt><dd>商品评论处理需求</dd></dl><p>每天有一批商品评论需要人工处理。请先做一个二分类基线，区分正向与负向评论。交付模型、评估结果和失败案例；不确定的评论交回人工。</p><p>内容运营组</p></div><h3>先把验收说清楚</h3><Select label="标签是什么？" value={data.label??''} onChange={label=>setData({label})} options={[["",'选择标签定义'],['binary','正向 / 负向'],['three','正向 / 负向 / 待复核']]}/><Select label="如何使用数据切分？" value={data.split??''} onChange={split=>setData({split})} options={[["",'选择数据使用方式'],['fixed','训练拟合，验证选模型，最后才打开测试'],['all','先用全部数据训练，再挑表现最好的样本']]}/><Select label="哪些情况需要人工复核？" value={data.review??''} onChange={review=>setData({review})} options={[["",'选择复核条件'],['uncertain','模型不确定或超出任务范围'],['negative','所有负向都直接自动退款']]}/>{error&&<Result ok={false}>{error}</Result>}<Submit onClick={()=>{if(data.label!=='binary'||data.split!=='fixed'||data.review!=='uncertain'){setError('任务是二分类；待复核是处理方式。测试数据留到选择结束，模型也没有自动退款权限。');return;}setError('');setData({accepted:true});commit('二分类标签；训练/验证/测试职责分开；不确定情况交回人工。');}}>确认任务，检查数据</Submit></section><section className="brief-data"><h2>你拿到的数据</h2><table><thead><tr><th>评论</th><th>标签 / 处理</th></tr></thead><tbody>{[['包装完整，质量不错','正向'],['物流慢，客服也没解决','负向'],['看起来不错，还没有用','待复核'],['价格不贵，效果很差','负向']].map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td></tr>)}</tbody></table><pre>{`X.shape = [${reviews.filter(r=>r.split==='train').length}, 16]\ny.shape = [${reviews.filter(r=>r.split==='train').length}]\n16 个词语的出现 / 未出现`}</pre><Note>教学合成数据，不代表真实业务表现。不同切分含有相似措辞，验证分数只能检查本实验机制，不能据此评估真实泛化。</Note><p>先修：向量与矩阵、导数与梯度、训练与验证的区别。遇到不熟悉的概念，可以打开本阶段的知识页。</p></section></div><section className="input-workshop"><h2>把一句评论变成模型的输入</h2><label className="work-field">输入评论<input value={example} maxLength={160} onChange={e=>setData({example:e.target.value})}/></label><FeatureVector text={example}/><p>向量只记录词语是否出现，没有保存词序，也没有理解否定。这种输入的局限会成为后面选择架构的理由。</p></section></>;
}
function Training({data,setData,commit}){
 const [live,setLive]=useState(null),[error,setError]=useState(''),worker=useRef(null),lr=data.lr??.3,runs=data.runs??[];
 useEffect(()=>()=>worker.current?.terminate(),[]);
 function train(){setError('');setLive({epoch:0,history:[]});const w=new Worker(new URL('../../journeys/train.worker.js',import.meta.url),{type:'module'});worker.current=w;w.onmessage=({data:message})=>{if(message.type==='progress')setLive(message);if(message.type==='done'){setData({runs:[...runs.slice(-2),message.run]});setLive(null);w.terminate();worker.current=null;}if(message.type==='error'){setError(message.message);setLive(null);w.terminate();worker.current=null;}};w.onerror=()=>{setError('训练线程没有正常启动，请重新运行。');setLive(null);w.terminate();worker.current=null;};w.postMessage({lr,seed:42,epochs:100});}
 const latest=runs.at(-1),history=live?.history??latest?.history??[];
 return <><h2>这一次，让参数真正更新。</h2><p>同一份词向量进入 16 → 8 → 1 的小网络：隐藏层用 tanh，输出用 sigmoid，优化二分类交叉熵。浏览器线程执行前向、解析反向梯度和全批次梯度下降。</p>{!data.accepted&&<Result ok={false}>先在第一章确认任务与数据约定，再开始训练。</Result>}<div className="training-console"><section><div className="network-chain"><span>16 维输入</span><i>→</i><span>8 个隐藏单元<br/><small>tanh</small></span><i>→</i><span>正向分数<br/><small>sigmoid</small></span></div><Sparkline series={[history.map(h=>h.train),history.map(h=>h.valid)]}/><p className="train-status" role="status">{live?`正在计算第 ${live.epoch} / 100 轮`:latest?`已计算 100 轮；最低验证损失位于第 ${latest.best.epoch} 轮`:'尚未运行。曲线会来自这次计算。'}</p></section><section><Range label="学习率" value={lr} onChange={lr=>setData({lr})} min={.01} max={3} step={.01}/><p>随机种子固定为 42；每次从同一初始参数开始，便于比较学习率。训练使用 {reviews.filter(r=>r.split==='train').length} 条合成评论。</p><button className="primary" disabled={!!live||!data.accepted} onClick={train}>{live?'训练中':'训练 100 轮'}</button>{live&&<button className="text-button" onClick={()=>{worker.current?.terminate();worker.current=null;setLive(null);setError('本次训练已停止，已完成的实验记录仍保留。');}}>停止本次训练</button>}<pre>{'for epoch in range(100):\n    logits = model(X_train)\n    loss = bce(logits, y_train)\n    grads = backward(loss)\n    parameters -= lr * grads\n    evaluate(X_valid)\n# 验证集不参与梯度更新'}</pre></section></div>{error&&<Result ok={false}>{error}</Result>}<Note>这是手写的小型多层感知机，不是浏览器里的 PyTorch。完整可运行的 PyTorch 对照脚本可在最后一章下载。验证分数来自合成小数据，不能作为上线承诺。</Note><Submit disabled={!latest||!!live} onClick={()=>commit(`种子 42，学习率 ${latest.lr}，100 轮；最低验证损失 ${Math.min(...latest.history.map(h=>h.valid)).toFixed(4)}。`)}>保存本次训练记录</Submit></>;
}
function ModelSelection({data,setData,commit}){
 const runs=data.runs??[],selected=data.selected??0;
 return <><h2>选择模型，看的是验证证据。</h2><p>回到上一章，用另一学习率再训练一次。这里保留最近三次实验；比较相同数据、初始化和训练轮数下的验证损失。</p><table className="runs-table"><thead><tr><th>选择</th><th>学习率</th><th>最低验证损失</th><th>对应轮数</th><th>最终训练损失</th></tr></thead><tbody>{runs.map((r,i)=><tr key={r.at}><td><input aria-label={'选择实验 '+(i+1)} type="radio" name="run" checked={selected===i} onChange={()=>setData({selected:i})}/></td><td>{r.lr}</td><td>{Math.min(...r.history.map(h=>h.valid)).toFixed(4)}</td><td>{r.best.epoch}</td><td>{r.history.at(-1).train.toFixed(4)}</td></tr>)}</tbody></table>{!runs.length&&<Result ok={false}>还没有训练记录。先运行一个基线，再来做选择。</Result>}<p>保存的是最低验证损失那一轮的参数，而不是最后一轮。测试集还没有参与选择。</p><Submit disabled={!runs[selected]} onClick={()=>{const r=runs[selected];setData({chosen:{model:r.best.model,epoch:r.best.epoch,lr:r.lr,seed:r.seed},testReport:null});commit(`选择学习率 ${r.lr}、第 ${r.best.epoch} 轮的参数；选择依据为验证损失。`);}}>冻结这个模型版本</Submit></>;
}
function Architecture({stage,data,setData,commit}){
 const position=data.window??0,reverse=data.reverse??false,query=data.queryIndex??0;
 const words=['价格','便宜','但是','质量','很差'],values=[0,1,0,0,-1],kernel=[-1,0,1],keys=[[1,0],[.8,.2],[0,1],[.5,.5],[-.8,1]],weights=attention(keys[query],keys),ordered=reverse?[...values].reverse():values;
 let h=0;const states=ordered.map(v=>{h=Math.tanh(.65*h+v);return h;});
 return <><h2>{stage===3?'一小段窗口，能捕捉什么线索？':stage===4?'词还是这些词，换顺序会怎样？':'每个位置应该从哪里读取信息？'}</h2><p>{stage===3?'词袋没有局部结构。让同一个三元素核沿着序列滑动，对照输入窗口和输出值。':stage===4?'词袋无法分辨顺序；递归状态把历史带到下一步。但固定状态也会逐渐弱化较早的信息。': '直接计算一次缩放点积注意力。点击查询位置，查看同一组 Q、K 如何改变权重。'}</p><div className="token-strip">{words.map((w,i)=><button key={w} className={(stage===3&&i>=position&&i<position+3)||(stage===5&&i===query)?'selected':''} onClick={()=>setData(stage===3?{window:Math.min(i,2)}:{queryIndex:i})}>{w}<small>{stage===5?`[${keys[i].join(', ')}]`:values[i]}</small></button>)}</div>{stage===3?<div className="architecture-output"><Range label="窗口起点" value={position} onChange={window=>setData({window})} min={0} max={2} step={1}/><pre>{`输入窗口 = [${values.slice(position,position+3).join(', ')}]\n卷积核 = [-1, 0, 1]\n输出 = ${values.slice(position,position+3).map((v,i)=>`${v}×${kernel[i]}`).join(' + ')}\n     = ${values.slice(position,position+3).reduce((s,v,i)=>s+v*kernel[i],0)}`}</pre><p>核参数在不同位置共享。这里按深度学习库常用的互相关方式计算，不翻转核；这不是已经训练好的情绪检测器。</p></div>:stage===4?<><label className="work-check"><input type="checkbox" checked={reverse} onChange={e=>setData({reverse:e.target.checked})}/>反转输入顺序</label><div className="state-chain">{states.map((v,i)=><div key={i}><span>输入 {ordered[i]}</span><b>h{i+1} = {v.toFixed(3)}</b></div>)}</div><pre>hₜ = tanh(0.65 × hₜ₋₁ + xₜ)，h₀ = 0</pre><p>权重 0.65 是教学设定。LSTM 通过门控管理信息的保留和更新，但本图没有模拟一个完整 LSTM。</p></>:<><div className="attention-bars">{weights.map((w,i)=><div key={i}><span>{words[i]}</span><div><i style={{width:w*100+'%'}}/></div><b>{(w*100).toFixed(1)}%</b></div>)}</div><pre>{`权重 = softmax(QKᵀ / √2)\n当前 Q = [${keys[query].join(', ')}]\n权重之和 = ${weights.reduce((a,b)=>a+b,0).toFixed(3)}`}</pre><p>这些向量是预设数值，不代表训练后的语义。Attention 只负责混合信息；Transformer 还包含位置、残差、归一化与前馈等结构。</p></>}<Note>这一章的产出是架构分析记录，不会把你的词袋 MLP 自动升级成 CNN、RNN 或 Transformer。要更换模型，需要另做训练与独立评估。</Note><Submit disabled={!data.chosen} onClick={()=>commit(stage===3?`窗口起点 ${position}，输出 ${values.slice(position,position+3).reduce((s,v,i)=>s+v*kernel[i],0)}；局部权重共享。`:stage===4?`输入${reverse?'反转':'原序'}，最终状态 ${states.at(-1).toFixed(3)}；词袋不能保留这种区别。`:`查询「${words[query]}」，注意力权重 ${weights.map(w=>w.toFixed(3)).join(', ')}。`)}>把架构观察加入项目档案</Submit>{!data.chosen&&<Note>先在第三章保存基线模型，让架构分析有明确的对照对象。</Note>}</>;
}
function SelfSupervision({data,setData,commit}){
 const masked=data.masked??1,words=['包装','完整','质量','不错'],[reveal,setReveal]=useState(false);
 return <><h2>没有人工标签，也能设计学习信号。</h2><p>运营希望利用未标注评论。先做一个遮词任务：输入来自原句，目标词也来自原句，情绪标签没有参与。但能补词不等于能正确分流。</p><div className="mask-workbench">{words.map((w,i)=><button key={w} className={i===masked?'selected':''} onClick={()=>{setData({masked:i});setReveal(false);}}>{i===masked&&!reveal?'[MASK]':w}</button>)}</div><button className="secondary" onClick={()=>setReveal(true)}>查看原句中的目标词</button>{reveal&&<Result>训练目标是「{words[masked]}」。本操作只是构造输入与目标，没有训练语言模型。</Result>}<Select label="应该用哪部分文本拟合预训练表示？" value={data.pretrain??''} onChange={pretrain=>setData({pretrain})} options={[["",'先选数据边界'],['train','预先允许使用的训练侧文本'],['test','把最终测试文本混入训练，分数越高越好']]}/><Select label="如何判断预训练是否有帮助？" value={data.compare??''} onChange={compare=>setData({compare})} options={[["",'选择对照方法'],['controlled','固定下游数据与预算，对照有无预训练'],['completion','只看补词是否流畅']]}/><p>下一步实验应记录语料范围、遮词规则、预训练预算和下游对照。不能拿一段流畅的补词结果代替分类评估。</p><Submit disabled={data.pretrain!=='train'||data.compare!=='controlled'||!data.chosen} onClick={()=>commit(`遮盖位置 ${masked}，目标「${words[masked]}」；只用允许的训练语料，固定下游预算比较有无预训练。`)}>保存预训练实验设计</Submit></>;
}
function Delivery({data,setData,commit,evidence}){
 const chosen=data.chosen,valid=validModel(chosen?.model),report=data.testReport,manual=data.manual??.15,text=data.tryText??'价格便宜，质量很差';
 const p=valid?forward(chosen.model,encode(text)).p:null,review=p!==null&&Math.abs(p-.5)<manual;
 const ready=Array.from({length:7},(_,i)=>!!evidence[i]).every(Boolean)&&valid;
 return <><h2>交付模型，也交付它做不到的事。</h2><p>现在拿同一份已冻结参数打开保留集。后面的生成式回复只作为需求讨论：当前分流器没有生成模型，也没有退款权限。</p><div className="delivery-layout"><section><h3>冻结版本</h3><pre>{valid?`学习率 ${chosen.lr}\n选择轮数 ${chosen.epoch}\n16 → 8 → 1，tanh / sigmoid\n参数与词表包含在交付文件`:'还没有选择模型。'}</pre><button className="primary" disabled={!ready||!!report} onClick={()=>setData({testReport:{...evaluate(chosen.model,reviews.filter(r=>r.split==='test')),at:Date.now()}})}>打开保留集评估</button>{!ready&&<Note>完成前七章的任务记录并保存模型后，才能验收。左侧可以返回缺少记录的阶段。</Note>}{report&&<><Result>保留集准确率 {(report.accuracy*100).toFixed(1)}%，交叉熵 {report.loss.toFixed(4)}。</Result><p>这份小样本结果只针对当前合成任务。没有测量业务误分成本、分布漂移或真实流量，不应据此上线。</p><h3>错误样本</h3>{report.predictions.filter(r=>(r.score>=.5?1:0)!==r.label).map(r=><p key={r.text}>{r.text} · 分数 {r.score.toFixed(3)} · 标签 {r.label?'正向':'负向'}</p>)}</>}</section><section><h3>用一个新句子找边界</h3><label className="work-field">输入评论<input value={text} maxLength={160} onChange={e=>setData({tryText:e.target.value})}/></label><Range label="距 0.5 多近时交回人工" value={manual} onChange={manual=>setData({manual})} min={.05} max={.4} step={.05}/>{valid&&<Result ok={!review}>模型分数 {p.toFixed(3)} · {review?'交回人工':p>=.5?'预测正向':'预测负向'}</Result>}<Note>sigmoid 输出不是经过校准的真实置信度。不在词表里的词不会被识别；即使分数极端，也可能因为否定、讽刺或新词而出错。</Note><label className="work-field">交接说明：一个失败场景与后续检查<textarea value={data.handoff??''} maxLength={3000} onChange={e=>setData({handoff:e.target.value})}/></label></section></div><div className="work-actions"><Submit disabled={!report||!data.handoff?.trim()} onClick={()=>{commit('冻结参数在保留集完成评估，已附失败边界与人工复核约定。');saveFile('nicoding-comment-classifier.json',{version:1,vocabulary,chosen,testReport:report,manualBand:manual,handoff:data.handoff,evidence,dataset:'Nicoding synthetic comments v1'});}}>保存并下载交付包</Submit><a className="secondary" href={`${import.meta.env.BASE_URL}learning/comment-classifier.py`} download>下载 PyTorch 对照脚本</a></div><Note>对照脚本需要本地安装 PyTorch；网页运行器没有预装它。网页报告与本地脚本都使用固定种子，但初始化实现不同，数值不要求完全一致。</Note></>;
}
export default function DeepLearningLab(props){const {stage}=props;return stage===0?<Brief {...props}/>:stage===1?<Training {...props}/>:stage===2?<ModelSelection {...props}/>:stage<6?<Architecture {...props}/>:stage===6?<SelfSupervision {...props}/>:<Delivery {...props}/>;}
