import React,{useRef,useState,useEffect} from 'react';
import {Range,Select,Note,Submit,Result} from './Primitives.jsx';
import {requestRace,couponRegression} from '../../journeys/models.js';

export function PythonLab({stage,data,setData,commit}){
 const input=data.input??'199, 299',step=data.step??0,copy=data.copy??false;
 const values=input.split(',').map(s=>s.trim());const valid=values.length>0&&values.every(v=>/^\d+$/.test(v)&&Number(v)<=100000);
 const nums=valid?values.map(Number):[],sum=nums.reduce((a,b)=>a+b,0),trace=[['读取订单','total = 0',0],...nums.map((n,i)=>['累加商品 '+(i+1),`total += ${n}`,nums.slice(0,i+1).reduce((a,b)=>a+b,0)]),['应用九折','total = total * 90 // 100',Math.floor(sum*.9)]];
 const cursor=Math.min(step,trace.length-1);
 return <><h2>{['先约定输入是什么','盯住变量，走完每一行','copy 之后，为什么原数据还变了？','把结果变成别人能接着用的数据'][stage]}</h2>
 {stage<2?<div className="work-columns"><section><label className="work-field">商品单价，单位为分<input value={input} onChange={e=>setData({input:e.target.value,step:0})} maxLength={100}/></label><p>用逗号分隔整数。接口传来的文字要先校验再转成数值；空值和负数不能悄悄变成有效订单。</p><pre>{'prices = [int(x) for x in raw.split(",")]\ntotal = 0\nfor price in prices:\n    total += price\ntotal = total * 90 // 100'}</pre><Note>金额使用整数分；先汇总再按九折向下取整。此处追踪的是这段预设程序。</Note></section><section className="trace-desk"><h3>执行轨迹</h3>{trace.map((r,i)=><button key={i} className={i===cursor?'current':''} onClick={()=>setData({step:i})}><span>{i+1}</span><code>{r[1]}</code><b>{i<=cursor?r[2]:'—'}</b></button>)}<div className="work-actions"><button className="secondary" disabled={!valid||cursor===0} onClick={()=>setData({step:cursor-1})}>上一步</button><button className="primary" disabled={!valid||cursor===trace.length-1} onClick={()=>setData({step:cursor+1})}>执行下一行</button></div></section></div>:null}
 {stage===2&&<><div className="work-columns"><section><pre>{'source = {"tags": ["新客"]}\nresult = source.copy()\n'+(copy?'result["tags"] = source["tags"].copy()\n':'')+'result["tags"].append("已优惠")'}</pre><label className="work-check"><input type="checkbox" checked={copy} onChange={e=>setData({copy:e.target.checked})}/>另外复制准备修改的 tags 列表</label></section><section className="object-pair"><div><span>source.tags</span><code>{copy?'["新客"]':'["新客", "已优惠"]'}</code></div><div><span>result.tags</span><code>["新客", "已优惠"]</code></div><Result ok={copy}>{copy?'修改边界已隔离，原始标签保留。':'外层字典不同，tags 仍指向同一个列表。'}</Result></section></div><a className="text-button" href="#learn/py-references">进入引用与复制完整实验 →</a></>}
 {stage===3&&<><pre>{JSON.stringify({currency:'CNY',unit:'分',items:nums,total:Math.floor(sum*.9),discountPercent:90},null,2)}</pre><p>下游需要知道数值单位和优惠规则。只有一个数字，没有约定，接口依然容易被误用。</p></>}
 {!valid&&<Result ok={false}>请输入非负整数分，例如 199, 299。空项目、负数和文字都不在本题契约内。</Result>}
 <Submit disabled={!valid||(stage===1&&cursor!==trace.length-1)||(stage===2&&!copy)} onClick={()=>commit(stage===0?`输入 ${nums.length} 个整数金额；单位为分。`:stage===1?`汇总 ${sum} 分，九折后 ${Math.floor(sum*.9)} 分。`:stage===2?'外层和 tags 分别复制，其他字段不作无关改动。':`交付 ${nums.length} 项订单的金额与单位契约。`)}>保存这一步的证据</Submit></>;
}

export function WebLab({stage,data,setData,commit}){
 const [running,setRunning]=useState(false),[events,setEvents]=useState([]),timers=useRef([]),active=useRef(null);
 const slow=data.slow??900,fast=data.fast??200,guard=data.guard??false,fail=data.fail??false;
 useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 function run(){timers.current.forEach(clearTimeout);setEvents([]);setRunning(true);active.current={slow,fast,guard,fail};const sequence=requestRace({slow,fast,guard,fail});sequence.forEach((e,i)=>{timers.current.push(setTimeout(()=>{setEvents(p=>[...p,e]);if(i===sequence.length-1){setRunning(false);setData({race:{slow,fast,guard,fail,events:sequence}});}},e.end));});}
 const visible=running?events:events.length?events:data.race?.events??[],shown=visible.at(-1)?.shown??'',lastConfig=running?active.current:data.race;
 return <><h2>{['页面应该忠实反映当前输入','亲手制造一次“旧结果覆盖”','只允许最新请求更新界面','请求失败时，用户看到什么？'][stage]}</h2><p>固定操作：0 ms 搜索「猫粮」，80 ms 后改成「猫砂」。分别调整两个响应的延迟，再观察真正的定时回调顺序。</p><div className="browser-bench"><section className="mock-browser"><header><i/><i/><i/><span>nicoding.local / search</span></header><div><label className="work-field">用户最后输入<input readOnly value="猫砂"/></label><p className="preview-status">{running?'正在接收响应…':lastConfig?.fail&&lastConfig?.guard?'猫砂搜索失败，请重试。':'搜索结果'}</p>{shown?<div className="search-preview"><strong>{shown==='猫砂'?'低尘豆腐猫砂':'成年猫主粮'}</strong><span>当前结果属于「{shown}」</span></div>:<p>运行实验后显示响应内容。</p>}</div></section><section><Range label="猫粮请求耗时" value={slow} onChange={slow=>setData({slow})} min={100} max={1500} step={100} suffix=" ms"/><Range label="猫砂请求耗时" value={fast} onChange={fast=>setData({fast})} min={100} max={1000} step={100} suffix=" ms"/><label className="work-check"><input type="checkbox" checked={guard} onChange={e=>setData({guard:e.target.checked})}/>用 requestId 忽略过期响应</label><label className="work-check"><input type="checkbox" checked={fail} onChange={e=>setData({fail:e.target.checked})}/>让猫砂请求返回错误</label><Submit disabled={running} onClick={run}>{running?'正在运行':'运行这次搜索'}</Submit></section></div><section className="waterfall"><h3>响应时间线</h3>{visible.map(e=><div key={e.id}><span>{e.query}</span><div><i style={{marginLeft:e.issued/18+'%',width:Math.max(5,(e.end-e.issued)/18)+'%'}}/></div><span>{e.end} ms · {e.error?'失败':e.applied?'更新界面':'忽略旧响应'}</span></div>)}</section><pre>{guard?'const id = ++latestRequest;\nconst result = await search(query);\nif (id === latestRequest) setResults(result);':'const result = await search(query);\nsetResults(result); // 没有检查请求是否过期'}</pre><Note>这里使用本地定时回调模拟响应，不发送真实网络请求。requestId 保护与 AbortController 取消职责不同；取消也不能替代结果归属检查。</Note><Submit disabled={running||!data.race||(stage===2&&(!data.race.guard||data.race.fail))||(stage===3&&(!data.race.guard||!data.race.fail))} onClick={()=>commit(`猫粮 ${data.race.slow} ms；猫砂 ${data.race.fast} ms；过期保护 ${data.race.guard?'开启':'关闭'}；失败场景 ${data.race.fail?'开启':'关闭'}。`)}>保存联调记录</Submit></>;
}

export function EngineeringLab({stage,data,setData,commit}){
 const [ran,setRan]=useState(false),[feedback,setFeedback]=useState('');const fix=data.fix??'client';
 const logs=['10:02:00.000  POST /redeem  key=order-104  attempt=1','10:02:00.040  coupon_balance: 2 → 1','10:02:01.000  client timeout; request may have succeeded','10:02:01.080  POST /redeem  key=order-104  attempt=2','10:02:01.120  coupon_balance: 1 → 0'];
 const regression=couponRegression(fix),tests=regression.map(r=>r.ok);
 return <><h2>{['一条反馈，不等于一个根因','把假设和日志对应起来','修复应该落在哪一层？','先验证正常情况，再制造并发'][stage]}</h2><div className="incident-layout"><section className="incident-log"><h3>订单 order-104 · 请求记录</h3>{logs.map((l,i)=><button key={l} className={data.log===i?'selected':''} onClick={()=>setData({log:i})}><span>{i+1}</span><code>{l}</code></button>)}<p>点选最能说明「重试造成重复副作用」的一行。</p></section><section><h3>调查笔记</h3><Select label="根因假设" value={data.cause??''} onChange={cause=>setData({cause})} options={[["",'选择一个可检验的假设'],['ui','按钮被点了两次'],['retry','相同业务请求被重复执行'],['cache','缓存失效导致余额显示错误']]}/><label className="work-field">为什么这条日志支持你的判断？<textarea value={data.reason??''} maxLength={2000} onChange={e=>setData({reason:e.target.value})}/></label><Note>文字记录供你自查；系统只核对结构化判断与模拟回归结果，不按字数评价推理质量。</Note></section></div>{stage>=2&&<><Select label="候选修复" value={fix} onChange={fix=>{setData({fix});setRan(false);}} options={[["client",'只禁用客户端按钮'],['check','服务端先查 key，再扣券，再写 key'],['atomic','服务端唯一幂等键 + 事务内扣券与记录']]}/><pre>{fix==='atomic'?'BEGIN\nINSERT request_key (key) VALUES (:key) -- UNIQUE\nUPDATE coupon SET balance = balance - 1\nSAVE response for :key\nCOMMIT\n-- 重试读取相同结果；整个事务原子提交':fix==='check'?'if not exists(key):\n    deduct_coupon()\n    save_key(key)\n# 两个并发请求可能都在写入前查到“不存在”':'button.disabled = true\n# 客户端超时重试或第二个客户端仍会发请求'}</pre><button className="secondary" onClick={()=>{setRan(true);setData({regression:{fix,tests}});}}>运行预设回归</button>{ran&&<ul className="regression-results">{['同一 key 连续请求只扣一次','不同 key 正常分别扣减','两个请求交错执行仍只扣一次'].map((t,i)=><li key={t}>{tests[i]?'✓':'×'} {t}<small>实际余额 {regression[i].balance} / 预期 {regression[i].expected}</small></li>)}</ul>}<Note>回归使用可复现的请求交错模型；它不连接真实数据库。生产实现还要覆盖事务回滚、幂等键作用域与过期策略。</Note></>}{feedback&&<Result ok={false}>{feedback}</Result>}<Submit onClick={()=>{if(data.cause!=='retry'||data.log!==4){setFeedback('请将相同 key 的第二次扣减与重复执行假设对应起来。');return;}if(stage>=2&&(data.regression?.fix!==fix||!data.regression?.tests.every(Boolean))){setFeedback('需要一份与当前修复一致、三项通过的回归记录。');return;}setFeedback('');commit(stage<2?'相同 order-104 重试后再次扣券；需要服务端幂等保护。':'唯一幂等键与扣券在同一事务内完成；顺序和交错请求均通过。');}}>保存调查结论</Submit></>;
}
