import React,{lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {journeys,journeySources} from '../../journeys/catalog.js';
import {paths} from '../../data/paths.js';
import {byId} from '../../data/index.js';
import {saveFile} from '../../journeys/records.js';
import {chapters,chapterNumber,completeChapter,missingRequirements} from '../../story/catalog.js';
import {ChapterRail} from '../../story/StoryViews.jsx';
import LessonText from '../LessonText.jsx';
import {Icon} from '../ui.jsx';
const PythonLab=lazy(()=>import('./FoundationLabs.jsx').then(m=>({default:m.PythonLab})));
const WebLab=lazy(()=>import('./FoundationLabs.jsx').then(m=>({default:m.WebLab})));
const EngineeringLab=lazy(()=>import('./FoundationLabs.jsx').then(m=>({default:m.EngineeringLab})));
const MathLab=lazy(()=>import('./AnalysisLabs.jsx').then(m=>({default:m.MathLab})));
const MLLab=lazy(()=>import('./AnalysisLabs.jsx').then(m=>({default:m.MLLab})));
const RLLab=lazy(()=>import('./AgentLabs.jsx').then(m=>({default:m.RLLab})));
const LLMLab=lazy(()=>import('./AgentLabs.jsx').then(m=>({default:m.LLMLab})));
const DeepLearningLab=lazy(()=>import('./DeepLearningLab.jsx'));
const labs={py:PythonLab,web:WebLab,eng:EngineeringLab,math:MathLab,ml:MLLab,dl:DeepLearningLab,rl:RLLab,llm:LLMLab};
const emptyRecord={version:1,stage:0,data:{},evidence:{},note:''};

export default function LearningJourney({id,stageParam,progress}){
 const spec=journeys[id],chapter=chapters[id],{state,setState}=progress,record=state.journeys?.[id]??emptyRecord;
 const index=stageParam===undefined?record.stage:Math.min(spec.stages.length-1,Math.max(0,Number(stageParam)||0));
 const [tab,setTab]=useState('story'),[exploring,setExploring]=useState(false),body=useRef(null),heading=useRef(null),Lab=labs[id];
 const beat=chapter.beats[index],lesson=byId[spec.lessons[index]],missing=missingRequirements(state,id),previous=index>0?record.evidence[index-1]:null;
 const skipped=index>0&&!previous;
 const update=useCallback(fn=>setState(s=>({...s,lastJourney:id,journeys:{...s.journeys,[id]:fn(s.journeys?.[id]??{...emptyRecord,data:{},evidence:{}})}})),[id,setState]);
 function setData(change){update(r=>({...r,data:{...r.data,...change},evidence:Object.fromEntries(Object.entries(r.evidence).filter(([step])=>Number(step)<index))}));}
 function commit(summary){update(r=>({...r,evidence:{...r.evidence,[index]:{summary,at:Date.now()}}}));setTab('outcome');window.dispatchEvent(new CustomEvent('nicoding-evidence'));}
 function choose(i){location.hash=`journey/${id}/${i}`;}
 useEffect(()=>{update(r=>({...r,stage:index}));setTab('story');setExploring(false);},[id,index,update]);
 useEffect(()=>{body.current?.scrollTo({top:0});heading.current?.focus({preventScroll:true});},[id,index,tab]);
 const finished=completeChapter(state,id),last=index===spec.stages.length-1;
 return <main className="story-frame story-workbench" data-domain={id} data-story={id} style={{'--story-accent':chapter.color,'--story-soft':chapter.soft,'--chapter-accent':chapter.color,'--chapter-soft':chapter.soft}}><ChapterRail id={id} state={state} index={index}/><section className="episode-main"><header className="episode-heading"><div><a href={'#chapter/'+id}>第 {chapterNumber(id)} 章 · {chapter.name}</a><h1 ref={heading} tabIndex={-1}>{String(index+1).padStart(2,'0')} / {spec.stages[index]}</h1></div><span>{beat[2]}</span></header><label className="story-mobile-select">本章小节<select value={index} onChange={e=>choose(Number(e.target.value))}>{spec.stages.map((s,i)=><option key={s} value={i}>{i+1}. {s}</option>)}</select></label><nav className="episode-tabs" aria-label="小节内容">{[['story','前情与任务'],['lab','动手实验'],['theory','原理与资料'],['record','本章档案']].map(([value,label])=><button key={value} className={tab===value||tab==='outcome'&&value==='lab'?'active':''} aria-pressed={tab===value} onClick={()=>setTab(value)}>{label}</button>)}</nav>
 <div ref={body} className="episode-scroll" tabIndex={0} aria-label="当前小节内容">
 {tab==='story'&&<section className="episode-prologue"><div className="episode-story-text"><span className="episode-stage-format"><Icon name={chapter.icon} size={19}/>{beat[2]}</span><h2>{beat[0]}</h2><p>{beat[1]}</p><blockquote><span>{chapter.sender}</span><p>{index===0?chapter.message:beat[3]}</p></blockquote></div><div className="episode-mission"><h3>这一步，带上什么</h3>{previous?<div className="handoff-record"><Icon name="FileCheck2" size={18}/><strong>{spec.outputs[index-1]}</strong><p>{previous.summary}</p></div>:index===0?<p>{chapter.requires.length?chapter.requires.map(r=>r.why).join('；'):'不需要先修。先观察本节的输入，再动手验证。'}</p>:<p>还没有「{spec.outputs[index-1]}」记录。<button className="story-link" onClick={()=>choose(index-1)}>回到上一节<Icon name="ArrowLeft" size={14}/></button></p>}<h3>完成以后留下什么</h3><p>{beat[3]}</p><div className="mission-output"><Icon name="Folder" size={17}/>{spec.outputs[index]}</div><button className="story-primary" onClick={()=>setTab('lab')}>{record.evidence[index]?'重新打开实验':'进入'+beat[2]}<Icon name="ArrowRight" size={18}/></button>{record.evidence[index]&&<button className="story-link" onClick={()=>setTab('outcome')}>查看已有结果<Icon name="ChevronRight" size={14}/></button>}</div></section>}
 {tab==='lab'&&<>{(skipped||missing.length>0)&&!exploring?<section className="episode-prerequisite"><Icon name="Route" size={30}/><h2>先接上前面的线索</h2><p>本节会用到下面这些基础。你可以先补齐，也可以带着问题直接探索；预览不会算作完成。</p>{skipped&&<a href={`#journey/${id}/${index-1}`}><span>上一节 · {spec.stages[index-1]}</span><small>需要：{spec.outputs[index-1]}</small><Icon name="ArrowRight"/></a>}{missing.map(r=><a key={r.id} href={'#chapter/'+r.id}><span>{chapters[r.id].subject} · {chapters[r.id].name}</span><small>{r.why}</small><Icon name="ArrowRight"/></a>)}<button className="story-link" onClick={()=>setExploring(true)}>直接探索本节<Icon name="ArrowRight" size={16}/></button></section>:<div className={'journey-content episode-lab journey-'+id}><div className="episode-goal"><Icon name="Target" size={17}/><span>{beat[3]}</span></div><Suspense fallback={<p role="status">正在准备实验…</p>}><Lab key={id+'-'+index} stage={index} data={record.data} setData={setData} commit={commit} evidence={record.evidence}/></Suspense></div>}</>}
 {tab==='outcome'&&<section className="episode-outcome"><div className="outcome-mark"><Icon name="Check" size={30}/></div><span>已保存本节实验记录</span><h2>{last?(finished?chapter.name+'，这一章交付了。':'这一步有记录了，还有前面的线索要补。'):spec.outputs[index]+'已放进档案。'}</h2><div className="outcome-evidence"><Icon name="FileCheck2" size={20}/><p>{record.evidence[index]?.summary??'尚未保存，请返回实验。'}</p></div><p className="outcome-narrative">{last?finished?chapter.ending:'完成本章其余小节的实验，才会形成完整交付。':chapter.beats[index+1][0]+' '+chapter.beats[index+1][1]}</p><div className="outcome-actions">{!last?<button className="story-primary" onClick={()=>choose(index+1)}>下一节：{spec.stages[index+1]}<Icon name="ArrowRight" size={18}/></button>:finished?<a className="story-primary" href={chapter.next.length?'#chapter/'+chapter.next[0]:'#projects'}>{chapter.next.length?'下一章：'+chapters[chapter.next[0]].name:'选择一个独立项目'}<Icon name="ArrowRight" size={18}/></a>:<button className="story-primary" onClick={()=>choose(spec.stages.findIndex((_,i)=>!record.evidence[i]))}>回到未完成的小节<Icon name="ArrowRight" size={18}/></button>}<button className="story-link" onClick={()=>setTab('record')}>查看本章档案</button></div><p className="outcome-footnote">记录来自本次实验；它不等于已经掌握整个技术方向。</p></section>}
 {tab==='theory'&&<article className="episode-theory"><h2>{lesson.title}</h2><p>{lesson.subtitle}</p>{lesson.parts.map(([title,text])=><section key={title}><h3>{title}</h3><LessonText text={text}/></section>)}<div className="episode-theory-links"><h3>继续查阅</h3><a href={'#learn/'+lesson.id}>完整知识页与练习<Icon name="ArrowUpRight" size={16}/></a><details><summary>本方向完整知识索引</summary>{paths[id].ids.map(lid=><a key={lid} href={'#learn/'+lid}>{byId[lid].title}</a>)}</details><h3>权威资料</h3>{journeySources[id].map(([name,url])=><a key={url} href={url} target="_blank" rel="noreferrer">{name}<Icon name="ExternalLink" size={14}/></a>)}</div></article>}
 {tab==='record'&&<section className="episode-records"><h2>{chapter.name} · 本章档案</h2><p>你的实验参数与结果保存在当前浏览器，重新进入小节会沿用这些数据。</p><ol>{spec.stages.map((s,i)=><li key={s}><span className={record.evidence[i]?'record-complete':''}>{record.evidence[i]?<Icon name="Check" size={16}/>:i+1}</span><div><a href={`#journey/${id}/${i}`}>{s}</a><p>{record.evidence[i]?.summary??'尚无实验记录'}</p></div></li>)}</ol><label className="work-field">留给下次的问题<textarea value={record.note} maxLength={16000} onChange={e=>{const note=e.target.value;update(r=>({...r,note}));}}/></label><button className="story-primary" onClick={()=>saveFile(`Nicoding-${id}-learning.json`,{title:spec.title,...record})}><Icon name="Download" size={17}/>导出本章档案</button><p className="work-note">这个文件用于阅读和交接。跨浏览器恢复全部记录，请使用顶部设置中的“导出进度”。</p></section>}
 </div><footer className="episode-footer"><a href={'#chapter/'+id}><Icon name="ArrowLeft" size={15}/>章节开篇</a><span>{Object.keys(record.evidence).length} / {spec.stages.length} 节有记录</span><button onClick={()=>setTab(record.evidence[index]?'outcome':'record')}>{record.evidence[index]?'本节结果':'查看进度'}<Icon name="ChevronRight" size={15}/></button></footer></section></main>;
}
