import React from 'react';
import {Range,Note,Submit} from './Primitives.jsx';

export default function MathLab({stage,data,setData,commit}) {
 const x=data.x??2,scale=data.scale??1,lr=data.lr??.2,prior=data.prior??10,trajectory=data.trajectory??[x];
 const bound=Math.max(4,Math.abs(x)*1.2,...trajectory.map(v=>Math.abs(v)*1.2)),px=t=>260+t/bound*230,py=t=>265-t/(bound*bound)*235;
 const points=Array.from({length:101},(_,i)=>{const t=-bound+i*bound/50;return `${px(t)},${py(t*t)}`;}).join(' ');
 const trueFlags=prior*8,falseFlags=(100-prior),posterior=trueFlags/(trueFlags+falseFlags),next=x-lr*2*x;
 const vectorBound=Math.max(4,Math.abs(x),Math.abs(x*scale))*1.15,vx=t=>260+t/vectorBound*230;
 function moveX(x){setData({x,trajectory:[x]});}
 return <><h2>{['一根向量经过矩阵，会去哪？','导数是当前点附近的变化率','梯度给方向，学习率给步长','被标记的订单，有多少确实异常？'][stage]}</h2>
 <div className="math-board"><div className="math-canvas">{stage===3?<div className="bayes-board" role="img" aria-label={`1000 笔订单中，${trueFlags} 笔异常订单被标记，${falseFlags} 笔正常订单被误标；标记后异常概率 ${(posterior*100).toFixed(1)}%`}><h3>从 1,000 笔订单往下数</h3><div className="bayes-branches"><section><span>确实异常</span><b>{prior*10}</b><p>其中 80% 被标记</p><strong>{trueFlags} 笔正确标记</strong></section><section><span>实际正常</span><b>{(100-prior)*10}</b><p>其中 10% 被误标</p><strong>{falseFlags} 笔错误标记</strong></section></div><h3>所有被标记的订单</h3><div className="probability-strip"><span style={{flex:trueFlags}}/><span style={{flex:falseFlags}}/></div><p>正确标记 {trueFlags} + 错误标记 {falseFlags} = {trueFlags+falseFlags} 笔</p><b className="bayes-answer">{(posterior*100).toFixed(1)}% 确实异常</b></div>:<svg viewBox="0 0 520 310" role="img" aria-label={stage===0?`向量 (${x},1)，变换后 (${x*scale},1)`:`函数 y=x²；x=${x}，导数=${2*x}；横轴范围 ±${bound.toFixed(1)}`}><defs><pattern id="math-grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#eae5de"/></pattern><clipPath id="math-area"><rect x="15" y="8" width="490" height="285"/></clipPath></defs><rect width="520" height="310" fill="url(#math-grid)"/><path d="M15 265H505M260 10V290" stroke="#bcb4a9"/><g clipPath="url(#math-area)">{stage===0?<><path d={`M260 265L${vx(x)} ${265-230/vectorBound}`} stroke="#c0a788" strokeWidth="3"/><path d={`M260 265L${vx(x*scale)} ${265-230/vectorBound}`} stroke="var(--chapter-accent)" strokeWidth="3"/><circle cx={vx(x*scale)} cy={265-230/vectorBound} r="6" fill="var(--chapter-accent)"/></>:<><polyline points={points} stroke="var(--chapter-accent)" strokeWidth="2.5" fill="none"/><path d={`M${px(-bound)} ${py(x*x+2*x*(-bound-x))}L${px(bound)} ${py(x*x+2*x*(bound-x))}`} stroke="#c0a788" strokeWidth="2"/>{stage===2&&trajectory.map((t,i)=><circle key={i} cx={px(t)} cy={py(t*t)} r="4" fill="#b39abe"/>)}<circle cx={px(x)} cy={py(x*x)} r="6" fill="var(--chapter-accent)"/></>}</g><text x="26" y="302">−{(stage===0?vectorBound:bound).toFixed(1)}</text><text x="250" y="302">0</text><text x="459" y="302">{(stage===0?vectorBound:bound).toFixed(1)}</text><text x="492" y="256">x</text><text x="272" y="21">y</text></svg>}</div>
 <section className="formula-desk">{stage===0?<><Range label="向量的 x 分量" value={x} onChange={moveX} min={-3} max={3} step={.25}/><Range label="矩阵横向缩放" value={scale} onChange={scale=>setData({scale})} min={-2} max={2} step={.1}/><pre>{`A = [[${scale}, 0], [0, 1]]\nv = [${x}, 1]\nAv = [${(x*scale).toFixed(2)}, 1]`}</pre><p>只缩放 x 轴，y 分量保持不变。负缩放还会翻转方向；坐标范围会随向量调整。</p></>:stage===3?<><Range label="异常订单的先验比例" value={prior} onChange={prior=>setData({prior})} min={1} max={90} step={1} suffix="%"/><p>假设规则能标出 80% 的异常订单，也会误标 10% 的正常订单。拖动异常比例，观察分母中混入多少正常订单。</p><pre>{`P(异常 | 被标记)\n= ${trueFlags} / (${trueFlags} + ${falseFlags})\n= ${(posterior*100).toFixed(1)}%`}</pre><Note>固定识别率，不代表固定的结果可信度。这是合成订单模型；条件概率需要结合基础比例。</Note></>:<><Range label="选择一个起始位置" value={Math.max(-3.5,Math.min(3.5,x))} onChange={moveX} min={-3.5} max={3.5} step={.1}/><pre>{`当前 x = ${x.toFixed(4)}\nf(x) = x² = ${(x*x).toFixed(4)}\nf′(x) = 2x = ${(2*x).toFixed(4)}`}</pre>{stage===2&&<><Range label="学习率 η" value={lr} onChange={lr=>setData({lr})} min={.05} max={1.1} step={.05}/><button className="secondary" disabled={Math.abs(next)>100000} onClick={()=>setData({x:next,trajectory:[...trajectory.slice(-14),next]})}>执行 x ← x − η·2x</button><p>下一步 x = {next.toFixed(4)}。η &gt; 1 时，绝对值会增大。图形自动缩放，计算值不被裁剪；浅色点保留最近 15 步。</p><button className="text-button" onClick={()=>moveX(3)}>从 x = 3 重新开始</button></>}</>}</section></div>
 <Submit onClick={()=>commit(stage===0?`向量 (${x},1) 经 diag(${scale},1) 变为 (${(x*scale).toFixed(2)},1)。`:stage===3?`异常先验 ${prior}%；标记后异常概率 ${(posterior*100).toFixed(1)}%。`:`x=${x.toFixed(4)}，导数=${(2*x).toFixed(4)}，学习率=${lr}。`)}>保存这组图与公式</Submit></>;
}
