import React,{useState} from 'react';
import {Icon} from '../components/ui.jsx';

export default function KnowledgeFigure({type}){
 const [x,setX]=useState(3),[mask,setMask]=useState(true),[shared,setShared]=useState(true);
 if(type==='autograd')return <figure className="atlas-figure"><div className="figure-tools"><label>x = {x}<input aria-label="计算图输入 x" type="range" min="-4" max="4" step=".5" value={x} onChange={e=>setX(+e.target.value)}/></label><span>y = x² + x</span></div><svg viewBox="0 0 680 205" role="img" aria-label={'x='+x+'，y='+(x*x+x)+'，梯度='+(2*x+1)}><defs><marker id="graph-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#7e8790"/></marker></defs><g className="figure-lines">{["M130 110L280 60","M330 60L480 110","M130 124L480 124","M530 120L600 120"].map(d=><path key={d} d={d} markerEnd="url(#graph-arrow)"/>)}</g>{[[105,120,'x',x],[305,55,'x²',x*x],[505,120,'+',x*x+x],[625,120,'y',x*x+x]].map(([cx,cy,label,value])=><g key={label}><circle cx={cx} cy={cy} r="24"/><text x={cx} y={cy+5} textAnchor="middle">{label}</text><text className="figure-value" x={cx} y={cy+47} textAnchor="middle">{value}</text></g>)}<g className="figure-gradient"><text x="220" y="35">2x = {2*x}</text><text x="300" y="157">直连贡献 = 1</text><text x="532" y="65">dy/dx = {2*x+1}</text></g></svg><figcaption>乘法路径贡献 2x，直连路径贡献 1；共享输入的梯度相加。</figcaption></figure>;
 if(type==='split')return <figure className="atlas-figure split-figure"><div className="split-stripe"><span>训练<small>拟合参数</small></span><span>验证<small>选择方案</small></span><span>测试<small>冻结后评估</small></span></div><div className="figure-tools"><label>评估对象<select aria-label="评估对象" value={shared?'new':'future'} onChange={e=>setShared(e.target.value==='new')}><option value="new">从未见过的新客户</option><option value="future">已有客户的未来记录</option></select></label></div><p>{shared?'新客户评估：同一客户整体放入同一集合，避免训练时已认识验证客户。':'未来记录评估：可以使用客户过去的数据，但特征和标签窗口必须严格早于预测时点。'}</p><figcaption>条形宽度仅示意分工，不规定必须采用某个比例。切分取决于部署问题。</figcaption></figure>;
 if(type==='attention')return <figure className="atlas-figure attention-figure"><div className="figure-tools"><span>4 个位置的可见关系</span><label><input type="checkbox" checked={mask} onChange={e=>setMask(e.target.checked)}/>因果遮罩</label></div><div className="attention-grid" role="img" aria-label={mask?'下三角因果可见矩阵':'所有位置彼此可见'}>{Array.from({length:16},(_,i)=>{const row=Math.floor(i/4),col=i%4,on=!mask||col<=row;return <span key={i} className={on?'allowed':''}>{on?'可见':'遮住'}<small>{row+1} → {col+1}</small></span>;})}</div><figcaption>{mask?'每个 query 只读取本位与更早的 key。':'关闭后可以读取未来位置；这不适合自回归训练。'} 此图表示允许关系，不是学习到的注意力权重。</figcaption></figure>;
 if(type==='references')return <figure className="atlas-figure"><div className="figure-tools"><span>外层列表复制以后</span><button className="atlas-link" onClick={()=>setShared(v=>!v)}>{shared?'改为深拷贝':'改为浅拷贝'}<Icon name="ArrowRight" size={15}/></button></div><div className="memory-figure"><code>a[0]</code><span>→</span><code>{'{"count": 2}'}</code><span>{shared?'←':'≠'}</span><code>{shared?'b[0]':'b[0] → {"count": 1}'}</code></div><figcaption>{shared?'浅拷贝：a[0] 和 b[0] 仍指向同一个字典；修改其中一个引用会被另一个看到。':'深拷贝：这个嵌套字典被复制，修改 a[0] 不再改变 b[0]。'}</figcaption></figure>;
 return null;
}

