import React,{useState} from 'react';
import {byId,lessons,projects,domains} from '../data/index.js';
import {Icon,Modal} from './ui.jsx';
import {Quiz,Editor} from './Lesson.jsx';
export function Review({progress,onLearn,onCelebrate}) {
 const [active,setActive]=useState(null),[passed,setPassed]=useState(false);
 const completed=lessons.filter(l=>progress.state.lessons[l.id]?.completed).sort((a,b)=>progress.state.lessons[a.id].due-progress.state.lessons[b.id].due);
 const due=completed.filter(l=>progress.state.lessons[l.id].due<=Date.now());
 return <main className="collection-page"><div className="collection-title"><span className="eyebrow">MAKE IT STAY</span><h1>把点亮的，再记牢一点。</h1><p>明天、三天后、一周后，再用自己的判断回答一次。</p></div><div className="review-summary"><span><b>{due.length}</b> 今天待复习</span><span><b>{completed.length}</b> 已点亮节点</span><span><Icon name="Clock"/>按实际完成时间安排</span></div>{completed.length?<div className="review-list">{completed.map(l=>{const r=progress.state.lessons[l.id],isDue=r.due<=Date.now();return <div className="review-row" key={l.id}><span className={`review-status ${isDue?'is-due':''}`}><Icon name={isDue?'RefreshCw':'CheckCircle2'}/></span><div><small>{domains.find(d=>d.id===l.domain).name}</small><h3>{l.title}</h3><p>{r.assisted?'上次借助了提示或纠错':'上次未使用提示'} · 已复习 {r.reviews||0} 次</p></div><time>{isDue?'现在可以回想':new Date(r.due).toLocaleDateString('zh-CN')+' 到期'}</time><button className="secondary" onClick={()=>{setActive(l);setPassed(false);}}>{isDue?'开始复习':'提前回想'}<Icon name="ArrowRight" size={15}/></button></div>;})}</div>:<div className="empty-state"><div className="empty-orb"><Icon name="Bookmark" size={28}/></div><h2>先留下一次有证据的进步。</h2><p>完成课程的理解检查和练习后，节点会自动进入复习计划。</p><button className="primary" onClick={()=>onLearn('py-values')}>从变量与对象开始<Icon name="ArrowRight"/></button></div>}{active&&<Modal wide title={`复习 · ${active.title}`} onClose={()=>setActive(null)}><Quiz key={active.id} lesson={active} review onPass={ok=>setPassed(ok)}/><div className="modal-footer"><button className="text-button" onClick={()=>{setActive(null);onLearn(active.id);}}>回到讲解<Icon name="ArrowRight" size={14}/></button><button className="primary" disabled={!passed} onClick={()=>{progress.review(active.id);setActive(null);onCelebrate();}}>记录本次复习<Icon name="Check"/></button></div></Modal>}</main>;
}
export function Projects({progress,onLearn,projectId,onProject}) {
 const active=projectId||projects[0].id;
 const [passed,setPassed]=useState(false);
 const selected=projects.find(p=>p.id===active),record={steps:[],note:'',...progress.state.projects[active]};
 function change(patch){progress.setState(s=>({...s,projects:{...s.projects,[active]:{steps:[],note:'',...s.projects[active],...patch}}}));}
 function toggle(i){change({steps:record.steps.includes(i)?record.steps.filter(x=>x!==i):[...record.steps,i]});}
 return <main className="collection-page project-page"><div className="collection-title"><span className="eyebrow">KNOWLEDGE INTO SOMETHING REAL</span><h1>学会之后，做点真的。</h1><p>先做 8 个可运行的小项目，再挑战 5 个综合交付。小项目检查核心逻辑，真实页面、数据和模型复现接着在本地完成。</p></div><div className="project-layout"><nav className="project-nav" aria-label="项目选择">{projects.map(p=><button key={p.id} className={active===p.id?'active':''} onClick={()=>{setPassed(false);onProject(p.id);}}><small>{p.label}{p.tier==='mini'?' · '+p.minutes:' · 综合项目'}</small><strong>{p.name}</strong><span>{progress.state.projects[p.id]?.steps?.length||0} / {p.steps.length} 项记录<Icon name="ArrowRight" size={15}/></span></button>)}</nav><article className="project-detail surface"><span className="eyebrow">{selected.label}</span><h2>{selected.name}</h2><p>{selected.intro}</p><div className="project-deliver"><Icon name="FileText"/><div><b>交付物</b><p>{selected.deliver}</p></div></div>{selected.tier==='mini'&&<div className="mini-project-workspace" key={active}><Editor lesson={{id:selected.id,lang:selected.lang,code:selected.starter,challenge:{task:'按需求完成核心函数，再运行行为与边界检查。',starter:selected.starter,solution:selected.solution,tests:selected.tests,hints:['先写一个最小正常例，在纸上得到期望输出。','再核对空输入、类型、边界和是否误改原数据。','把验证结果中的失败条件逐条对应到契约。']}}} challengeMode onEvidence={setPassed} onAssist={()=>{}} savedCode={record.code} onCodeChange={code=>{change({code});setPassed(false);}}/><p className="mini-check-status" role="status">{passed?'本轮预设检查已通过，继续补充自己的例子与解释。':'运行检查验证核心逻辑；行动清单用于记录完整项目证据。'}</p><div className="mini-stretch"><h3>再往前一步</h3><p>{selected.stretch}</p></div></div>}<h3>行动清单</h3><div className="project-checks">{selected.steps.map((step,i)=><label key={step}><input type="checkbox" checked={record.steps.includes(i)} onChange={()=>toggle(i)}/><span>{step}</span></label>)}</div><div className="acceptance"><Icon name="Target"/><div><h3>可检查的验收标准</h3><p>{selected.accept}</p></div></div><h3>用到的知识</h3><div className="chips">{selected.skills.map(id=><button key={id} onClick={()=>onLearn(id)}>{byId[id].title}<Icon name="ChevronRight" size={14}/></button>)}</div><label className="project-note">证据与复盘 <small>自动保存到本机</small><textarea value={record.note||''} onChange={e=>change({note:e.target.value})} maxLength={20000} placeholder="粘贴项目地址、测试结果摘要、遇到的问题，以及你能独立解释的部分。"/></label><p className="fineprint">清单由你手动核对；勾选不会自动认证项目质量，也不会替代课程练习。</p></article></div></main>;
}
