import React from 'react';
import {byId,domains,lessons,projects} from '../data/index.js';
import {branches,paths,placements,reasons,nextLesson,firstMissingPrereq,pathCompletion} from '../data/paths.js';
import {Icon,statusOf,statusLabel} from './ui.jsx';

const domainById=Object.fromEntries(domains.map(d=>[d.id,d]));
const number=n=>String(n).padStart(2,'0');
export function Prerequisites({lesson,records}) {
 return <div className="path-prereqs"><span>建议先会</span>{lesson.prereqs.length?lesson.prereqs.map(id=><a key={id} href={`#learn/${id}`} className={records[id]?.completed?'is-complete':''}><Icon name={records[id]?.completed?'CheckCircle2':'BookOpen'} size={12}/>{byId[id].domain!==lesson.domain&&<small>{domainById[byId[id].domain].short} · </small>}{byId[id].title}</a>):<span className="no-prereqs">无需先修，从这里开始</span>}</div>;
}
function DomainCard({id,records}) {
 const d=domainById[id],path=paths[id],done=pathCompletion(id,records);
 return <a className="domain-card" href={`#path/${id}`} style={{'--domain-color':d.color}}><div className="domain-card-top"><span className="domain-symbol"><Icon name={d.icon} size={22}/></span><span>{done} / {path.ids.length} 点亮</span><Icon name="ArrowRight" size={17}/></div><h3>{d.name}</h3><p>{d.caption}</p><div className="domain-chapter-preview">{path.chapters.map((c,i)=><span key={c.title}>{number(i+1)} {c.title.replace('可选进阶：','进阶 · ')}</span>)}</div><progress value={done} max={path.ids.length} aria-label={`${d.name}完成进度`}/></a>;
}
export function Roadmap({state}) {
 const done=lessons.filter(l=>state.lessons[l.id]?.completed).length;
 const last=byId[state.last],started=last&&state.lessons[last.id]?.visited&&!state.lessons[last.id]?.completed;
 const target=started?last.id:lessons.find(l=>!state.lessons[l.id]?.completed&&l.prereqs.every(id=>state.lessons[id]?.completed))?.id;
 const suggested=target?byId[target]:null;
 return <main className="roadmap-page"><div className="roadmap-intro"><div><span className="eyebrow">YOUR LEARNING ATLAS</span><h1>让知识，长成一条路。</h1><p>先读懂代码，再选择应用或算法。每个方向都有顺序，每一步都能回到实际项目。</p></div><div className="atlas-progress"><b>{done}<small> / {lessons.length}</small></b><span>知识节点已点亮</span><progress value={done} max={lessons.length}/></div></div>
  <section className="continue-strip" aria-label="学习建议"><span className="continue-icon"><Icon name="Sparkles" size={24}/></span><div><small>{suggested?(started?'接着上次，往前一点':'从这里开始下一步'):'所有节点已点亮'}</small><h2>{suggested?suggested.title:'用真实交付，检验你的理解'}</h2><p>{suggested?`${domainById[suggested.domain].name} · ${reasons[suggested.id]}`:'回到项目，把分散的知识连成一个作品。'}</p></div><a className="primary" href={suggested?`#learn/${suggested.id}`:'#projects'}>{suggested?'进入课程':'去做项目'}<Icon name="ArrowRight" size={17}/></a></section>
  <div className="branch-guide"><Icon name="Route" size={17}/><p>共同基础打底后，两条分支可以按目标选择、交叉学习。AI 应用的前 6 节不要求先学完深度学习。</p><span>8 个方向 · 60 节课程</span></div>
  <div className="branch-grid">{branches.map(b=><section className={`learning-branch branch-${b.id}`} key={b.id} aria-label={b.title}><div className="branch-heading"><span>{b.eyebrow}</span><h2>{b.title}</h2><p>{b.description}</p></div><div className="branch-cards">{b.domains.map(id=><DomainCard id={id} records={state.lessons} key={id}/>)}</div>{b.id==='application'&&<a className="branch-project" href="#projects/agentproject"><Icon name="PawPrint" size={23}/><span className="eyebrow">MAKE SOMETHING REAL</span><h3>会查证、会停止的知识助手</h3><p>把上下文、工具、检索和评估接到一起，让 Nico 见证你的第一次完整交付。</p><span className="text-button">查看实践项目<Icon name="ArrowRight" size={16}/></span></a>}</section>)}</div>
  <p className="atlas-footnote"><Icon name="LockKeyhole" size={13}/>进度保存在当前浏览器 · 点亮需要完成课程检查 · 可在设置中导出备份</p>
 </main>;
}
export function DomainPath({id,state}) {
 const d=domainById[id],path=paths[id],done=pathCompletion(id,state.lessons),next=nextLesson(id,state.lessons);
 const missing=next&&firstMissingPrereq(next,state.lessons),project=projects.find(p=>p.id===path.project);
 function jump(index){document.getElementById(`chapter-${index}`)?.scrollIntoView({block:'start',behavior:'instant'});document.getElementById(`chapter-${index}`)?.focus({preventScroll:true});}
 return <main className="path-page" style={{'--domain-color':d.color}}><aside className="path-sidebar"><a className="back-link" href="#explore"><Icon name="ArrowLeft" size={16}/>全部学习方向</a><nav className="path-domains" aria-label="学习方向">{branches.flatMap(b=>b.domains).map(domain=><a href={`#path/${domain}`} key={domain} aria-current={domain===id?'page':undefined}><Icon name={domainById[domain].icon} size={16}/><span>{domainById[domain].name}</span><small>{pathCompletion(domain,state.lessons)}/{paths[domain].ids.length}</small></a>)}</nav><div className="chapter-index"><span className="eyebrow">本方向的学习阶段</span>{path.chapters.map((c,i)=><button key={c.title} onClick={()=>jump(i)}><span>{number(i+1)}</span>{c.title}</button>)}</div><div className="path-goal"><Icon name="Target"/><h3>完成后，你能</h3><p>{path.outcome}</p></div></aside>
  <div className="path-main"><header className="path-heading"><div className="breadcrumb"><a href="#explore">学习路线</a><span>/</span>{d.name}</div><div className="path-title-line"><span className="domain-symbol"><Icon name={d.icon} size={27}/></span><h1>{d.name}</h1><span className="path-count">{done}<small> / {path.ids.length} 点亮</small></span></div><p className="path-lead">{path.lead}</p><p className="path-entry">{path.entry}</p><div className="path-start-row"><a className="primary" href={next?`#learn/${next}`:`#projects/${project.id}`}>{next?(done?'继续本方向':'开始本方向'):'用项目巩固'}<Icon name="ArrowRight" size={16}/></a>{missing&&<span>还没学过先修？<a href={`#learn/${missing}`}>先补「{byId[missing].title}」<Icon name="ArrowRight" size={13}/></a></span>}</div></header>
   <div className="path-legend"><span><i className="legend-line"/>编号是建议学习顺序</span><span><Icon name="BookOpen" size={13}/>每节下方列出直接先修</span><span><i className="legend-glow"/>优先掌握</span></div>
   {path.chapters.map((c,i)=><section className="path-chapter" id={`chapter-${i}`} tabIndex={-1} key={c.title}><header><span className="chapter-number">{number(i+1)}</span><div><h2>{c.title}</h2><p>{c.reason}</p></div><span className="chapter-count">{c.ids.filter(id=>state.lessons[id]?.completed).length}/{c.ids.length}</span></header><ol className="lesson-chain" start={placements[c.ids[0]].index+1}>{c.ids.map(lessonId=>{const l=byId[lessonId],record=state.lessons[lessonId],status=statusOf(record);return <li className={`path-node ${l.priority===1?'priority':''} ${status}`} key={lessonId} data-lesson={lessonId}><a className="path-lesson-link" href={`#learn/${lessonId}`}><span className="path-node-orb">{record?.completed?<Icon name="Check" size={20}/>:number(placements[lessonId].index+1)}</span><span className="path-node-copy"><span className="path-node-title">{l.title}{l.priority===1&&<small>优先</small>}</span><span className="path-node-reason">{reasons[lessonId]}</span></span><span className="path-node-meta"><span>{statusLabel[status]}</span><small>{l.minutes} 分钟起</small></span><Icon name="ArrowRight" size={18}/></a><Prerequisites lesson={l} records={state.lessons}/></li>;})}</ol><div className="chapter-outcome"><Icon name="Flag" size={15}/><span>这一阶段的成果</span><p>{c.outcome}</p></div></section>)}
   <section className="path-destination"><span className="eyebrow">把这条路，走进项目</span><h2>{project.name}</h2><p>{project.intro}</p><a className="primary" href={`#projects/${project.id}`}>查看交付与验收<Icon name="ArrowRight" size={16}/></a><div className="path-next-domains"><span>接下来可以连接</span>{path.next.map(id=><a href={`#path/${id}`} key={id}>{domainById[id].name}<Icon name="ArrowRight" size={14}/></a>)}</div></section>
  </div></main>;
}
