import React,{useCallback,useLayoutEffect,useRef} from 'react';
import {Icon} from '../../components/ui.jsx';
import PracticeLab from '../../components/learning/PracticeLab.jsx';
import {byId} from '../../data/index.js';
import {COURSE,parts,units,unitById,courseHref,fresh,unitDone,completed} from './registry.js';
import {content,sources} from './content.js';
import {tasks} from './tasks.js';
import {Concept,Training,Decision,Handoff} from './Labs.jsx';
import './bank.css';

function Quiz({unit,record,patch}){
 const spec=content[unit.id].quiz,a=record.answers?.[unit.id],checked=!!a?.checked;
 return <section className="bank-quiz" aria-label="理解检查"><div className="bank-section-caption"><Icon name="CircleHelp" size={18}/><span>停一下，检查理解</span></div><h3>{spec.question}</h3><fieldset><legend className="sr-only">{spec.question}</legend>{spec.options.map((option,i)=><label key={option} className={a?.choice===i?'selected':''}><input type="radio" name={'quiz-'+unit.id} checked={a?.choice===i} onChange={()=>patch(r=>({...r,answers:{...r.answers,[unit.id]:{choice:i,checked:false}}}))}/><span>{option}</span></label>)}</fieldset><button className="secondary" disabled={a?.choice===undefined} onClick={()=>patch(r=>({...r,answers:{...r.answers,[unit.id]:{...r.answers[unit.id],checked:true}}}))}>核对解释</button>{checked&&<p className={'bank-feedback '+(a.choice===unit.answer?'correct':'retry')} role="status"><Icon name={a.choice===unit.answer?'CheckCircle2':'CircleHelp'} size={18}/>{spec.feedback[a.choice]}</p>}</section>;
}
export default function BankCourse({unitId,progress}){
 const {state,setState}=progress,record=state.courses?.[COURSE]||fresh(),unit=unitById[unitId],index=units.findIndex(u=>u.id===unitId),scrollRef=useRef(),headingRef=useRef();
 const patch=useCallback(change=>setState(s=>({...s,lastCourse:COURSE,lastJourney:null,courses:{...s.courses,[COURSE]:change(s.courses?.[COURSE]||fresh())}})),[setState]);
 useLayoutEffect(()=>{if(unitId)patch(r=>({...r,last:unitId}));scrollRef.current?.scrollTo(0,0);headingRef.current?.focus({preventScroll:true});headingRef.current?.closest('main')?.querySelector('.bank-rail a[aria-current="step"]')?.scrollIntoView({block:'nearest',inline:'nearest'});},[unitId,patch]);
 const count=completed(record),next=units.find(u=>!unitDone(record,u))||units.at(-1),currentPart=parts.find(p=>p.ids.includes(unitId));
 return <main className="bank-course"><aside className="bank-rail"><a className="back-link" href="#explore"><Icon name="ArrowLeft" size={15}/>全部章节</a><div className="bank-rail-brand"><span>机器学习 · 第一部分</span><h2>从原始数据<br/>训练第一个模型</h2></div><nav aria-label="机器学习课程目录"><a className={'bank-overview-link '+(!unit?'active':'')} aria-current={!unit?'page':undefined} href="#chapter/ml"><Icon name="Layers" size={17}/>项目开篇<span>4,521 条真实记录</span></a>{parts.map((part,i)=><div className="bank-rail-part" key={part.title}><h3><span>{String(i+1).padStart(2,'0')}</span>{part.title}</h3>{part.ids.map(id=>{const u=unitById[id],done=unitDone(record,u);return <a key={id} href={courseHref(id)} aria-current={id===unitId?'step':undefined} className={id===unitId?'active':''}><span className={'bank-node '+(done?'done':'')}>{done?<Icon name="Check" size={12}/>:record.read?.[id]?<i/>:String(units.indexOf(u)+1).padStart(2,'0')}</span><span>{u.title}<small>{u.format}</small></span></a>;})}</div>)}</nav><div className="bank-rail-foot"><span>{count} / {units.length} 节已留齐学习证据</span><progress max={units.length} value={count} aria-label="本部分学习证据进度"/><a href="#path/ml">算法知识索引<Icon name="ArrowUpRight" size={14}/></a></div></aside>
 <section className="bank-stage"><header className="bank-title"><div><span>{unit?currentPart.title:'ML / PROJECT 01'}</span><h1 ref={headingRef} tabIndex={-1}>{unit?unit.title:'这一轮，联系谁？'}</h1></div><a href={unit?'#chapter/ml':'#library'}>{unit?'课程总览':'知识索引'}<Icon name="ArrowUpRight" size={15}/></a></header><div className="bank-scroll" ref={scrollRef} key={unitId||'opening'}>
 {!unit?<div className="bank-opening"><div className="bank-opening-hero"><div><span className="bank-eyebrow">一张表 → 一份可以复核的实验</span><h2>把“模型说了算”<br/>变成你能解释的决定。</h2><p>接下一个银行营销分类任务，从读入 CSV 开始，亲手写预处理和梯度更新，训练模型，再决定哪些结果值得相信。</p><div className="bank-opening-actions"><a className="primary" href={courseHref(record.last||next.id)}>{record.last?'回到上次的小节':'查看任务书'}<Icon name="ArrowRight" size={17}/></a><span>12 小节 · 约 5–7 小时<br/><small>可拆开完成，时间按基础与练习情况浮动</small></span></div></div><div className="bank-project-card"><div className="bank-project-label"><span>项目档案 / 001</span><Icon name="FileCode2" size={20}/></div><h3>第一份分类模型</h3><div className="bank-project-flow">{[['01','读记录','CSV → X, y'],['02','训练','预测 → 梯度 → 更新'],['03','决定','错误 → 阈值 → 验收']].map(([n,t,d])=><div key={n}><b>{n}</b><span>{t}<small>{d}</small></span><Icon name="ChevronRight" size={15}/></div>)}</div><dl><div><dt>数据</dt><dd>UCI · 4,521 条</dd></div><div><dt>实现</dt><dd>Python / NumPy</dd></div><div><dt>交付</dt><dd>代码、参数与报告</dd></div></dl></div></div>
 <div className="bank-opening-facts"><span><Icon name="Code2"/>4 组可运行代码练习</span><span><Icon name="SlidersHorizontal"/>4 个概念实验</span><span><Icon name="FlaskConical"/>真实训练与错误分析</span><span><Icon name="Download"/>可下载，能在本地复算</span></div>
 <section className="bank-parts"><div className="bank-section-caption"><span>本部分的四段任务</span><small>按依赖往下走，也可以先预览</small></div>{parts.map((part,i)=><div className="bank-part-card" key={part.title}><div><span className="bank-part-number">0{i+1}</span><h3>{part.title}</h3><p>{part.description}</p></div><ol>{part.ids.map(id=><li key={id}><a href={courseHref(id)}><span>{unitById[id].title}</span><small>{unitById[id].format}</small><Icon name={unitDone(record,unitById[id])?'CheckCircle2':'ArrowRight'} size={16}/></a></li>)}</ol></div>)}</section>
 <section className="bank-prereqs"><h3>需要先会多少？</h3><p>会读变量、列表和函数即可开始。涉及标准化、概率与导数的地方都安排了例子，代码练习提供逐步提示。卡住时可用每节的补课入口，不需要先学完所有数学。</p><div><a href="#learn/py-functions">Python 函数</a><a href="#learn/math-vectors">向量与矩阵</a><a href="#learn/math-grad">导数与梯度</a></div></section><aside className="bank-scope"><h3>这一批做到哪里</h3><p>这一部分完成逻辑回归项目的完整流程。树模型、集成、聚类及深度学习复现会继续按独立部分展开。已有的<a href="#journey/ml">阈值情境演示</a>与<a href="#path/ml">算法知识索引</a>仍可作为补充。</p></aside><p className="bank-attribution">数据：Moro 等，Bank Marketing，UCI Machine Learning Repository · <a href={sources.data[1]} target="_blank" rel="noreferrer">来源与 CC BY 4.0 授权</a>。课程讲解与练习为 Nicoding 原创。</p></div>
 :<article className={'bank-unit bank-unit-'+unit.id}><div className="bank-unit-meta"><span>{String(index+1).padStart(2,'0')} / 12</span><span>{unit.format}</span><span>约 {unit.minutes} 分钟</span>{unitDone(record,unit)&&<span className="bank-evidence"><Icon name="Check" size={14}/>本节证据已留齐</span>}</div><p className="bank-lead">{content[unit.id].lead}</p><div className="bank-goal"><Icon name="Flag" size={18}/><span>{content[unit.id].goal}</span></div>{index>0&&!unitDone(record,units[index-1])&&<p className="bank-prior">这一节接着<a href={courseHref(units[index-1].id)}>{units[index-1].title}</a>。可以预览；若遇到不熟悉的概念，先回去补一下。</p>}
 <div className="bank-prose">{content[unit.id].sections.map((section,i)=><section key={section.title}><h2><span>{i+1}</span>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}</div>{content[unit.id].code&&<pre className="bank-code">{content[unit.id].code}</pre>}
 <Concept key={'concept-'+unit.id} id={unit.id}/>{unit.task&&<PracticeLab key={unit.task} task={tasks[unit.task]} record={record} patch={patch}/>}
 {unit.id==='train'&&<Training record={record} patch={patch}/>}
 {unit.id==='decision'&&<Decision record={record} patch={patch}/>}
 {unit.id==='handoff'&&<Handoff record={record} patch={patch}/>}
 <Quiz key={'quiz-'+unit.id} unit={unit} record={record} patch={patch}/>
 <div className="bank-resource-row"><details className="bank-detail"><summary>核对资料与补课入口</summary><p>讲解为原创，以下是核对定义与深入阅读的资料：</p><ul>{content[unit.id].sources.map(id=><li key={id}><a href={sources[id][1]} target="_blank" rel="noreferrer">{sources[id][0]} ↗</a></li>)}</ul>{content[unit.id].bridge.filter(id=>byId[id]).map(id=><a className="bank-bridge" href={'#learn/'+id} key={id}>{byId[id].title}<Icon name="ArrowUpRight" size={13}/></a>)}</details><button className="text-button" aria-pressed={!!record.read?.[unit.id]} onClick={()=>patch(r=>({...r,read:{...r.read,[unit.id]:!r.read?.[unit.id]}}))}><Icon name={record.read?.[unit.id]?'Check':'BookOpen'} size={16}/>{record.read?.[unit.id]?'已读过':'记为已读'}</button></div>
 <p className="bank-muted bank-completion-hint">{unitDone(record,unit)?'本节所需的检查与实践记录已保存。':'理解题需核对正确'+(unit.task?'，代码需通过全部检查且保持未修改':'')+(unit.id==='train'?'，需完成单因素对照并写至少 20 字结论':'')+(unit.id==='decision'?'，需冻结方案并完成测试':'')+(unit.id==='handoff'?'，需留下至少 100 字交付说明与测试报告':'')+'。阅读记录与完成证据分开保存。'}</p><nav className="bank-unit-nav" aria-label="小节翻页">{index>0?<a className="secondary" href={courseHref(units[index-1].id)}><Icon name="ArrowLeft" size={16}/>上一节</a>:<a className="secondary" href="#chapter/ml">项目开篇</a>}{index<units.length-1?<a className="primary" href={courseHref(units[index+1].id)}>下一节：{units[index+1].title}<Icon name="ArrowRight" size={16}/></a>:<a className="primary" href="#chapter/ml">返回课程总览<Icon name="ArrowRight" size={16}/></a>}</nav></article>}
 </div></section></main>;
}
