export const tasks={
 encode:{id:'encode',title:'把记录拆成 X 与 y',filename:'encode.py',contract:'实现 encode(rows)。按 age、balance 顺序返回 (X,y)，数值转 float，yes→1、no→0，不修改输入。空输入返回 ([],[])。',starter:'def encode(rows):\n    X = []\n    y = []\n    for row in rows:\n        X.append([row["age"], row["balance"]])\n        y.append(int(bool(row["y"])))\n    return X, y\n\nprint(encode([{"age":"30", "balance":"120", "y":"no"}]))',solution:'def encode(rows):\n    X = [[float(r["age"]), float(r["balance"])] for r in rows]\n    y = [int(r["y"] == "yes") for r in rows]\n    return X, y',hints:['CSV 字段是字符串，考虑 float()。','bool("no") 也是 True，直接比较是否等于 "yes"。','每条记录创建新列表，不改原字典。'],tests:[
 {name:'yes 与 no 正确编码',code:'assert encode([{"age":"20","balance":"3","y":"no"},{"age":"45","balance":"-9","y":"yes"}]) == ([[20.0,3.0],[45.0,-9.0]],[0,1])'},
 {name:'数值是 float',code:'assert all(type(v) is float for v in encode([{"age":"28","balance":"0.5","y":"yes"}])[0][0])'},
 {name:'空输入有定义',code:'assert encode([]) == ([], [])'},
 {name:'输入未改，行不共享',code:'import copy\nr=[{"age":"20","balance":"4","y":"yes"},{"age":"21","balance":"5","y":"no"}]; before=copy.deepcopy(r)\nx,y=encode(r); x[0][0]=999\nassert r==before and x[1][0]==21.0'}]},
 scale:{id:'scale',title:'只在训练集拟合',filename:'scale.py',contract:'standardize(train,values) 用 train 的均值与总体标准差转换 values，返回新列表。零标准差按 1 处理，空 train 报 ValueError。',starter:'def standardize(train, values):\n    mean = sum(values) / len(values)\n    scale = (sum((x-mean)**2 for x in values) / len(values))**0.5\n    return [(x-mean)/scale for x in values]\n\nprint(standardize([20,40], [50,60]))',solution:'def standardize(train, values):\n    if not train:\n        raise ValueError("empty training data")\n    mean = sum(train)/len(train)\n    scale = (sum((x-mean)**2 for x in train)/len(train))**0.5\n    if scale == 0:\n        scale = 1\n    return [(x-mean)/scale for x in values]',hints:['mean、scale 都从 train 计算。','总体方差除以 len(train)，本题不估计无偏样本方差。','train 为空无法拟合；全相同时 scale=1。'],tests:[
 {name:'复用训练坐标系',code:'assert standardize([20,40],[50,60]) == [2.0,3.0]'},
 {name:'常数列与空验证集',code:'assert standardize([3,3],[4,2]) == [1.0,-1.0]\nassert standardize([1,2],[]) == []'},
 {name:'空训练明确报错',code:'try:\n    standardize([], [5])\nexcept ValueError:\n    pass\nelse:\n    raise AssertionError("需要 ValueError")'},
 {name:'负值与输入不变',code:'t=[-2,2]; v=[-4,0,4]\nassert standardize(t,v)==[-2.0,0.0,2.0]\nassert t==[-2,2] and v==[-4,0,4]'}]},
 step:{id:'step',title:'实现一次梯度更新',filename:'gradient_step.py',contract:'step(xs,ys,w,b,lr,l2) 返回 (新 w,新 b)。单特征批量平均梯度，w 使用 L2，b 不惩罚。至少一条记录，数值较小。',starter:'import math\n\ndef step(xs, ys, w, b, lr, l2):\n    errors = [1/(1+math.exp(-(w*x+b)))-y for x,y in zip(xs,ys)]\n    grad_w = sum(e*x for e,x in zip(errors,xs))\n    grad_b = sum(errors)\n    return w+lr*grad_w, b+lr*grad_b\n\nprint(step([1,2], [0,1], 0, 0, 0.2, 0))',solution:'import math\n\ndef step(xs, ys, w, b, lr, l2):\n    errors = [1/(1+math.exp(-(w*x+b)))-y for x,y in zip(xs,ys)]\n    grad_w = sum(e*x for e,x in zip(errors,xs))/len(xs)+l2*w\n    grad_b = sum(errors)/len(xs)\n    return w-lr*grad_w, b-lr*grad_b',hints:['对每条记录的梯度求平均。','下降用减号，w 梯度加 l2*w。','b 梯度只有平均误差，没有 l2*b。'],tests:[
 {name:'手算样本一致',code:'w,b=step([1,2],[0,1],0,0,.2,0)\nassert abs(w-.05)<1e-10 and abs(b)<1e-10'},
 {name:'重复样本不改变平均梯度',code:'a=step([1,2],[0,1],.3,-.1,.2,0)\nb=step([1,2,1,2],[0,1,0,1],.3,-.1,.2,0)\nassert all(abs(x-y)<1e-10 for x,y in zip(a,b))'},
 {name:'L2 只惩罚权重',code:'a=step([0],[1],2,1,.1,0)\nb=step([0],[1],2,1,.1,.5)\nassert abs(a[0]-b[0]-.1)<1e-10 and abs(a[1]-b[1])<1e-10'},
 {name:'这一步降低预测损失',code:'xs=[-1,1]; ys=[0,1]\nw,b=step(xs,ys,0,0,.1,0)\nloss=sum(math.log1p(math.exp(w*x+b))-y*(w*x+b) for x,y in zip(xs,ys))/2\nassert loss < math.log(2)\nassert xs==[-1,1] and ys==[0,1]'}]},
 budget:{id:'budget',title:'实现预算内名单',filename:'select_budget.py',contract:'select_budget(rows,k) 返回分数降序、同分 id 升序的前 k 个 id。k 为整数，负数报 ValueError，不修改 rows。',starter:'def select_budget(rows, k):\n    # 补全实现\n    return []\n\nprint(select_budget([{"id":3,"p":.8},{"id":1,"p":.8},{"id":2,"p":.9}], 2))',solution:'def select_budget(rows, k):\n    if k < 0:\n        raise ValueError("k must be nonnegative")\n    ranked = sorted(rows, key=lambda r: (-r["p"], r["id"]))\n    return [r["id"] for r in ranked[:k]]',hints:['sorted() 返回新列表，list.sort() 修改原列表。','复合排序键可以是 (-分数, id)。','先检查负 k 再切片；负数切片有其他含义。'],tests:[
 {name:'分数优先，同分稳定',code:'assert select_budget([{"id":3,"p":.8},{"id":1,"p":.8},{"id":2,"p":.9}],2)==[2,1]'},
 {name:'零预算和空输入',code:'assert select_budget([{"id":1,"p":.9}],0)==[]\nassert select_budget([],5)==[]'},
 {name:'超额预算与输入不变',code:'import copy\nr=[{"id":9,"p":.1},{"id":4,"p":.7}]; old=copy.deepcopy(r)\nassert select_budget(r,20)==[4,9] and r==old'},
 {name:'负预算报错',code:'try:\n    select_budget([], -1)\nexcept ValueError:\n    pass\nelse:\n    raise AssertionError("负预算应报 ValueError")'}]},
};
