import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './App.jsx';
import './styles.css';
import './interaction.css';
import './roadmap.css';
import './clarity.css';
import './project-studio.css';
import './learning/unit.css';
createRoot(document.getElementById('root')).render(<App/>);
